europeana/annotation

annotation-client/src/test/java/eu/europeana/annotation/client/integration/admin/AnnotationApiAdminTest.java
annotation-client/src/test/java/eu/europeana/annotation/client/integration/webanno/BaseWebAnnotationProtocolTest.java
annotation-solr/src/main/java/eu/europeana/annotation/solr/model/internal/SolrAnnotationImpl.java
annotation-solr/src/test/resources/solr/annotation/conf/schema.xml

Change-Id: Id0f1cfc92a08a533b390c3ae536bdc9670e7f84f

#135 removed internal type and updated tests

---

annotation-mongo/src/main/java/eu/europeana/annotation/mongo/model/internal/PersistentAnnotation.java
annotation-mongo/src/main/java/eu/europeana/annotation/mongo/service/PersistentAnnotationServiceImpl.java

Change-Id: Ifb43ea54a14740df2bc5a5a4b767165869e57217

#136 completely remove the usage of resourceId field

---

annotation-mongo/src/main/java/eu/europeana/annotation/mongo/service/PersistentApiWriteLockService.java
annotation-mongo/src/main/java/eu/europeana/annotation/mongo/service/PersistentApiWriteLockServiceImpl.java
annotation-web/src/main/java/eu/europeana/annotation/web/exception/IndexingJobLockedException.java
annotation-web/src/main/java/eu/europeana/annotation/web/service/authorization/AuthorizationServiceImpl.java
annotation-web/src/main/java/eu/europeana/annotation/web/service/controller/admin/ManagementRest.java
annotation-web/src/main/java/eu/europeana/annotation/web/service/impl/AdminServiceImpl.java

API write lock/unlock independent from indexing lock

#131 implement locking mechanism for reindexing jobs

---

annotation-utils/src/main/java/eu/europeana/annotation/utils/serialize/AnnotationLdSerializer.java
annotation-utils/src/main/java/eu/europeana/annotation/utils/serialize/AnnotationPageSerializer.java
pom.xml

Change-Id: Iabf08e38de149f6bec830154dfaae3042877546b

#153 code changes for annotation-ld 1.1.3

---

annotation-definitions/src/main/java/eu/europeana/annotation/definitions/model/Annotation.java
annotation-definitions/src/main/java/eu/europeana/annotation/definitions/model/utils/AnnotationsList.java
annotation-mongo/src/main/java/eu/europeana/annotation/mongo/dao/PersistentAnnotationDaoImpl.java
annotation-mongo/src/main/java/eu/europeana/annotation/mongo/model/PersistentAnnotationImpl.java
annotation-mongo/src/main/java/eu/europeana/annotation/mongo/service/PersistentAnnotationService.java
annotation-mongo/src/main/java/eu/europeana/annotation/mongo/service/PersistentAnnotationServiceImpl.java
annotation-utils/src/main/java/eu/europeana/annotation/utils/serialize/AnnotationPageSerializer.java
annotation-web/src/main/java/eu/europeana/annotation/web/service/AnnotationService.java
annotation-web/src/main/java/eu/europeana/annotation/web/service/controller/jsonld/BaseJsonldRest.java
annotation-web/src/main/java/eu/europeana/annotation/web/service/impl/AnnotationServiceImpl.java

Change-Id: I52d4fd2f0c6f816bac4393d13b8d98eed9c46055

#152 Batch annotation upload: annotation page output

---

annotation-client/src/test/java/eu/europeana/annotation/client/integration/webanno/BatchUploadTest.java
annotation-definitions/src/main/java/eu/europeana/annotation/definitions/model/vocabulary/WebAnnotationFields.java
annotation-mongo/src/main/java/eu/europeana/annotation/mongo/dao/PersistentAnnotationDaoImpl.java
annotation-mongo/src/main/java/eu/europeana/annotation/mongo/model/internal/GeneratedAnnotationIdImpl.java
annotation-utils/src/main/java/eu/europeana/annotation/utils/serialize/AnnotationPageSerializer.java
annotation-web/src/main/java/eu/europeana/annotation/web/service/controller/jsonld/BaseJsonldRest.java

Change-Id: Ie095eb93a904011397e5c5681830245048c7a363

#152 Batch upload: Fix serialization bug; adapt unit test

---

annotation-mongo/pom.xml
annotation-mongo/src/main/java/eu/europeana/annotation/mongo/dao/PersistentAnnotationDao.java
annotation-mongo/src/main/java/eu/europeana/annotation/mongo/dao/PersistentAnnotationDaoImpl.java
annotation-mongo/src/main/java/eu/europeana/annotation/mongo/service/PersistentAnnotationServiceImpl.java
annotation-mongo/src/test/java/eu/europeana/annotation/mongo/dao/PersistentAnnotationDaoTest.java

Change-Id: I43ede5eca97ac7422e83c53c8a6356d28164b019

#152 Batch upload optimization: generate sequence of annotation IDs

---

annotation-web/src/main/java/eu/europeana/annotation/web/model/vocabulary/Actions.java
annotation-web/src/main/java/eu/europeana/annotation/web/model/vocabulary/Operations.java
annotation-web/src/main/java/eu/europeana/annotation/web/model/vocabulary/UserGroups.java
annotation-web/src/main/java/eu/europeana/annotation/web/service/AdminService.java
annotation-web/src/main/java/eu/europeana/annotation/web/service/authorization/AuthorizationServiceImpl.java
annotation-web/src/main/java/eu/europeana/annotation/web/service/controller/admin/ManagementRest.java
annotation-web/src/main/java/eu/europeana/annotation/web/service/impl/AdminServiceImpl.java

https://app.assembla.com/spaces/europeana-apis/tickets/realtime_cardwall?ticket=629

#163 api write lock must not prevent reindexing

---

annotation-definitions/src/main/java/eu/europeana/annotation/definitions/model/vocabulary/WebAnnotationFields.java
annotation-utils/src/main/java/eu/europeana/annotation/config/AnnotationConfiguration.java
annotation-utils/src/main/java/eu/europeana/annotation/config/AnnotationConfigurationImpl.java
annotation-web/pom.xml
annotation-web/src/main/java/eu/europeana/annotation/web/service/AdminService.java
annotation-web/src/main/java/eu/europeana/annotation/web/service/authentication/AuthenticationService.java
annotation-web/src/main/java/eu/europeana/annotation/web/service/controller/BaseRest.java
annotation-web/src/main/java/eu/europeana/annotation/web/service/controller/admin/ManagementRest.java
annotation-web/src/main/java/eu/europeana/annotation/web/service/controller/admin/WhitelistRest.java
annotation-web/src/main/java/eu/europeana/annotation/web/service/controller/jsonld/BaseJsonldRest.java
annotation-web/src/main/java/eu/europeana/annotation/web/service/controller/jsonld/WebAnnotationSearchRest.java
annotation-web/src/main/java/eu/europeana/annotation/web/service/impl/AdminServiceImpl.java
annotation-web/src/test/java/eu/europeana/annotation/web/service/impl/AnnotationClientApiKeyValidationTest.java

validation method in admin console.

#173 Integrated validation using apikey client library. Created related

---

annotation-client/src/test/java/eu/europeana/annotation/client/integration/webanno/transcribe/BaseTranscribingTest.java
annotation-client/src/test/java/eu/europeana/annotation/client/integration/webanno/transcribe/EdmTranscribingWithRightsTest.java
annotation-client/src/test/resources/link/wrong/standard_jsonld.json
annotation-client/src/test/resources/transcription/transcription-with-rights.json
annotation-definitions/src/main/java/eu/europeana/annotation/definitions/model/resource/SpecificResource.java
annotation-definitions/src/main/java/eu/europeana/annotation/definitions/model/resource/impl/BaseSpecificResource.java
annotation-definitions/src/main/java/eu/europeana/annotation/definitions/model/vocabulary/WebAnnotationFields.java
annotation-utils/src/main/java/eu/europeana/annotation/config/AnnotationConfiguration.java
annotation-utils/src/main/java/eu/europeana/annotation/config/AnnotationConfigurationImpl.java
annotation-utils/src/main/java/eu/europeana/annotation/utils/parse/AnnotationLdParser.java
annotation-utils/src/main/java/eu/europeana/annotation/utils/serialize/AnnotationLdSerializer.java
annotation-web/src/main/java/eu/europeana/annotation/web/service/impl/AnnotationServiceImpl.java
api2-common/src/main/resources/config/annotation.properties.template

Implemented rights filed handling for transcriptions body. Created JUnit test.

#213 EA-1873 added rights field to transcriptions body.

---

annotation-solr/src/main/java/eu/europeana/annotation/solr/model/internal/SolrAnnotationImpl.java
annotation-solr/src/main/java/eu/europeana/annotation/solr/service/impl/SolrAnnotationServiceImpl.java
annotation-solr/src/main/java/eu/europeana/annotation/solr/service/impl/SolrAnnotationUtils.java
annotation-web/src/main/java/eu/europeana/annotation/web/service/impl/AnnotationServiceImpl.java

Change-Id: Ieff465e14661945b94fb9cb8e374ffad717d9ad0

#229 basic implementation of indexing for transcription values

---

annotation-client/src/test/java/eu/europeana/annotation/client/integration/webanno/tag/DereferencedSemanticTaggingTest.java
annotation-dereferenciation/src/main/resources/deref2json.xsl

Change-Id: I9e4a07f77354bcc300043f9776e0d4319319e3d0

#215 fixed xsl mapping for numeric values

---

annotation-dereferenciation/src/main/java/eu/europeana/annotation/dereferenciation/MetisDereferenciationClient.java

Change-Id: Ibf6d231b44e9de841412dc880d47dbc9f0187d52

#215 deref must not use a default lang

---

annotation-dereferenciation/src/main/java/eu/europeana/annotation/dereferenciation/MetisDereferenciationClient.java

Change-Id: I9b4c6ec86056751581b8ed2cfd130a86eccb9973

#215 the langs param must be ste only if not null

---

annotation-client/src/main/java/eu/europeana/annotation/client/config/ClientConfiguration.java
annotation-client/src/main/java/eu/europeana/annotation/client/connection/AnnotationApiConnection.java
annotation-client/src/main/java/eu/europeana/annotation/client/webanno/WebAnnotationProtocolApi.java
annotation-client/src/main/java/eu/europeana/annotation/client/webanno/WebAnnotationProtocolApiImpl.java
annotation-client/src/main/resources/annotation-client.properties.template
annotation-client/src/test/java/eu/europeana/annotation/client/integration/webanno/BaseWebAnnotationProtocolTest.java
annotation-client/src/test/java/eu/europeana/annotation/client/integration/webanno/tag/BaseTaggingTest.java
annotation-client/src/test/java/eu/europeana/annotation/client/integration/webanno/tag/DereferencedSemanticTaggingTest.java
annotation-client/src/test/resources/semantictag/dereferenced_semantictag_viaf_test_entity2.json
annotation-client/src/test/resources/semantictag/dereferenced_semantictag_viaf_test_entity3.json

JUnit tests for dereferenciation for getAnnotation with only JWT token and multiple languages

Add JUnit tests

---

annotation-solr/src/main/java/eu/europeana/annotation/solr/service/impl/SolrAnnotationUtils.java
annotation-web/src/main/java/eu/europeana/annotation/web/exception/request/ParamValidationException.java
annotation-web/src/main/java/eu/europeana/annotation/web/model/vocabulary/UserRoles.java
annotation-web/src/main/java/eu/europeana/annotation/web/service/AnnotationService.java
annotation-web/src/main/java/eu/europeana/annotation/web/service/authorization/AuthorizationServiceImpl.java
annotation-web/src/main/java/eu/europeana/annotation/web/service/controller/jsonld/BaseJsonldRest.java
annotation-web/src/main/java/eu/europeana/annotation/web/service/impl/AnnotationServiceImpl.java
annotation-web/src/main/java/eu/europeana/annotation/web/service/impl/BaseAnnotationServiceImpl.java

UserGroup to UserRole, creator and generator must not be overwritten
during update
Change-Id: I5e2e94318733e6f5c5bd266b7d766242c64e2232

#239 added ownership verification for delete and update, renamed

---

annotation-web/src/main/java/eu/europeana/annotation/web/service/controller/admin/WhitelistRest.java
pom.xml

Change-Id: I674913756d8ad18cc7c29c8c16508160a366c32a

#219 fixed permission verification for whitelist loading

---

annotation-client/pom.xml

Change-Id: Ida65a874ab7d8ee4a18bb0bee4db750f16c498ab

#219 removed unused test dependency

---

annotation-import/pom.xml

Change-Id: I77fa449183a32d06608c71ae8348dd7d9a7b39c8

#249 enable jar will dependencies

---

annotation-import/src/main/java/eu/europeana/annotation/synchronize/AnnotationSynchronizer.java
annotation-import/src/main/java/eu/europeana/annotation/synchronize/BaseAnnotationSynchronizer.java

operations performed
Change-Id: I7289b288db8c1619a0d7414734ff1110118197cc

#249 updated script to log the number of updated records and upda

---

annotation-import/src/main/java/eu/europeana/annotation/synchronize/AnnotationSynchronizer.java

Change-Id: I94573c1ee9545c4adeb880fbe37cc14afb0eccbd

#249 avoid NPE

---

annotation-client/src/test/java/eu/europeana/annotation/client/integration/webanno/tag/BaseTaggingTest.java
annotation-client/src/test/java/eu/europeana/annotation/client/integration/webanno/tag/BodyTypesTest.java
annotation-client/src/test/java/eu/europeana/annotation/client/integration/webanno/tag/SearchTypesTest.java
annotation-web/src/main/java/eu/europeana/annotation/web/service/impl/AnnotationServiceImpl.java

Implemented tests for search for different body types

#238 EA-1916 implemented tests for search for different body types

---

annotation-client/pom.xml
annotation-client/src/main/java/eu/europeana/annotation/client/connection/AnnotationApiConnection.java
annotation-definitions/src/main/java/eu/europeana/annotation/definitions/model/vocabulary/WebAnnotationFields.java
annotation-web/src/main/java/eu/europeana/annotation/web/service/controller/jsonld/BaseJsonldRest.java
annotation-web/src/main/java/eu/europeana/annotation/web/service/controller/jsonld/WebAnnotationAuxiliaryMethods.java
annotation-web/src/main/java/eu/europeana/annotation/web/service/controller/jsonld/WebAnnotationFeedbackRest.java
annotation-web/src/main/java/eu/europeana/annotation/web/service/controller/jsonld/WebAnnotationProtocolRest.java
annotation-web/src/main/java/eu/europeana/annotation/web/service/impl/AnnotationSearchServiceImpl.java

Common constants for Web fields moved to api-commons

#260 common constants moved to api-commons

---

annotation-definitions/src/main/java/eu/europeana/annotation/definitions/model/vocabulary/AnnotationScenarioTypes.java
annotation-solr/src/main/java/eu/europeana/annotation/solr/model/internal/SolrAnnotation.java
annotation-solr/src/main/java/eu/europeana/annotation/solr/model/internal/SolrAnnotationImpl.java
annotation-solr/src/main/java/eu/europeana/annotation/solr/vocabulary/SolrAnnotationConstants.java
annotation-solr/src/test/resources/solr7-dev/anno-dev/anno-up/conf/schema.xml

(transcriptions, subtitles, smeatic_tags, etc.)

introducing a new solr field for the annotations scenarios types

---

annotation-solr/src/main/java/eu/europeana/annotation/solr/service/impl/SolrAnnotationServiceImpl.java

linkForContributing duplication check updated to consider only the

---

pom.xml

changed default test execution to skip, it can be enabled though command
